### PR TITLE
Convert the documentation PS to PDF and include again in tarballs

### PR DESCRIPTION
**Pull request by pmatilai**
The pdf is about 1/6 of the size with no quality loss that I can tell.
It's actual professionally written documentation even if a bit outdated,
might as well include it. Also fixup the reference in the README.

### CODE REVIEW

**Comment by ffesti** [comment]
Did you just manually convert the file and checked it in? Or is this created somehow?

**Comment by pmatilai** [comment]
Just ran it through ps2pdf.

**Comment by ffesti** [comment]
Ok!

Kinda weird that it shrinks that much as PDF is basically PS on the inside AFAIK. But PDF clearly is more useful nowadays.

I would be great to get the actual sources for this but I guess chances are very slim on that.

**Comment by pmatilai** [comment]
Stupid LGTM thingie got stuck on checking something that doesn't contain code-changes at all :roll_eyes: Rebased just to see if happens to get unstuck with that...

**Pull request merged**
